import { describe, it, test, before, after, beforeEach } from 'node:test';
import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import http from 'node:http';
import { MemoryChallengeStore, RedisChallengeStore, CONFIG } from '../src/storage.mjs';
import { createAdminChallenge, issueAdminSession, verifyEd25519, signEd25519, authorizeSession, revokeAdminSession, delegateCapabilities, ToolRouter, createHighImpactConfirmation, signActionConfirmation } from '../src/auth.mjs';
import { GlimmerProvider, MODEL_ID, runLilyProof } from '../src/provider.mjs';

const ownerId='owner-test-12345678';let publicPem,privatePem,device;
const resetKeys=()=>{const {publicKey,privateKey}=crypto.generateKeyPairSync('ed25519');publicPem=publicKey.export({type:'spki',format:'pem'});privatePem=privateKey.export({type:'pkcs8',format:'pem'});device={id:'device-1',publicKeyPem:publicPem}};
async function makeSession(store,id=ownerId,audit){const ch=await createAdminChallenge(store,id);const sig=signEd25519({...ch,privateKeyPem:privatePem});return issueAdminSession({store,challenge:ch,signedChallenge:sig,authenticatedUser:{id},verifiedDevice:device,audit})}

describe('Lily owner admin hardened',()=>{
  beforeEach(resetKeys);
  it('verifies only Ed25519 domain-separated challenge signatures',async()=>{const store=new MemoryChallengeStore(),ch=await createAdminChallenge(store,ownerId),sig=signEd25519({...ch,privateKeyPem:privatePem});assert.equal(await verifyEd25519({...ch,signedChallenge:sig,publicKeyPem:publicPem}),true);assert.equal(await verifyEd25519({...ch,nonce:ch.nonce+'00',signedChallenge:sig,publicKeyPem:publicPem}),false)});
  it('rejects challenge tampering and wrong device signatures',async()=>{const store=new MemoryChallengeStore(),ch=await createAdminChallenge(store,ownerId),sig=signEd25519({...ch,privateKeyPem:privatePem});await assert.rejects(()=>issueAdminSession({store,challenge:{...ch,createdAt:ch.createdAt+1},signedChallenge:sig,authenticatedUser:{id:ownerId},verifiedDevice:device}),/CHALLENGE_TAMPERED/);const other=crypto.generateKeyPairSync('ed25519'),otherPriv=other.privateKey.export({type:'pkcs8',format:'pem'}),ch2=await createAdminChallenge(store,ownerId),badSig=signEd25519({...ch2,privateKeyPem:otherPriv});await assert.rejects(()=>issueAdminSession({store,challenge:ch2,signedChallenge:badSig,authenticatedUser:{id:ownerId},verifiedDevice:device}),/SIGNATURE_INVALID/)});
  it('consumes each admin nonce once under concurrency',async()=>{const store=new MemoryChallengeStore(),ch=await createAdminChallenge(store,ownerId),sig=signEd25519({...ch,privateKeyPem:privatePem}),results=await Promise.allSettled(Array.from({length:20},()=>issueAdminSession({store,challenge:ch,signedChallenge:sig,authenticatedUser:{id:ownerId},verifiedDevice:device})));assert.equal(results.filter(r=>r.status==='fulfilled').length,1);assert.equal(results.filter(r=>r.status==='rejected'&&/CHALLENGE_REPLAYED/.test(r.reason.message)).length,19)});
  it('enforces expiry lockout and session limit',async()=>{const store=new MemoryChallengeStore(),expired=await createAdminChallenge(store,ownerId);store.challenges.get(expired.nonce).expiresAt=Date.now()-1;const sig=signEd25519({...expired,privateKeyPem:privatePem});await assert.rejects(()=>issueAdminSession({store,challenge:expired,signedChallenge:sig,authenticatedUser:{id:ownerId},verifiedDevice:device}),/CHALLENGE_EXPIRED/);const lockOwner='owner-lockout-12345678';for(let i=0;i<CONFIG.MAX_ATTEMPTS;i++){const c=await createAdminChallenge(store,lockOwner);await assert.rejects(()=>issueAdminSession({store,challenge:c,signedChallenge:'AAAA',authenticatedUser:{id:lockOwner},verifiedDevice:device}),/SIGNATURE_INVALID/)}await assert.rejects(()=>createAdminChallenge(store,lockOwner),/OWNER_LOCKED/);const owner2='owner-sessions-12345678';await makeSession(store,owner2);await makeSession(store,owner2);await assert.rejects(()=>makeSession(store,owner2),/MAX_CONCURRENT_SESSIONS/)});
  it('supports immediate server-side revocation',async()=>{const store=new MemoryChallengeStore(),session=await makeSession(store);await authorizeSession(store,session,'system.health');assert.equal(await revokeAdminSession(store,session),true);await assert.rejects(()=>authorizeSession(store,session,'system.health'),/ADMIN_SESSION_REVOKED/)});
  it('rejects client-side capability forgery with a valid session id',async()=>{const store=new MemoryChallengeStore(),session=await makeSession(store),forged={...session,capabilities:[...session.capabilities,'production.deploy']};await assert.rejects(()=>authorizeSession(store,forged,'production.deploy'),/CAPABILITY_DENIED/)});
  it('narrows delegated capabilities from server claims',async()=>{const store=new MemoryChallengeStore(),parent=await makeSession(store),child=await delegateCapabilities(store,parent,['task.create','production.deploy','system.health']);assert.deepEqual(child.capabilities,['task.create','system.health']);await authorizeSession(store,child,'system.health');await assert.rejects(()=>authorizeSession(store,child,'production.deploy'),/CAPABILITY_DENIED/)});
  it('binds high-impact confirmation and prevents replay',async()=>{const store=new MemoryChallengeStore(),session=await makeSession(store),router=new ToolRouter({store,audit:async()=>{}});router.register({name:'deploy',capability:'task.create',highImpactAction:'production.deploy',handler:async()=>'done'});const taskId='task-abc';await assert.rejects(()=>router.execute({tool:'deploy',session,taskId,devicePublicKeyPem:publicPem}),/EXPLICIT_CONFIRMATION_REQUIRED/);const c=await createHighImpactConfirmation(store,session,'production.deploy',taskId),signature=signActionConfirmation({...c,privateKeyPem:privatePem});await assert.rejects(()=>router.execute({tool:'deploy',session,taskId:'other',confirmation:{id:c.id,signature},devicePublicKeyPem:publicPem}),/CONFIRMATION_SCOPE_MISMATCH/);const c2=await createHighImpactConfirmation(store,session,'production.deploy',taskId),sig2=signActionConfirmation({...c2,privateKeyPem:privatePem});assert.equal((await router.execute({tool:'deploy',session,taskId,confirmation:{id:c2.id,signature:sig2},devicePublicKeyPem:publicPem})).result,'done');await assert.rejects(()=>router.execute({tool:'deploy',session,taskId,confirmation:{id:c2.id,signature:sig2},devicePublicKeyPem:publicPem}),/CONFIRMATION_REPLAYED/)});
  it('propagates audit id and blocks tools after revocation',async()=>{const store=new MemoryChallengeStore(),events=[],session=await makeSession(store);let calls=0;const router=new ToolRouter({store,audit:async e=>events.push(e)});router.register({name:'health',capability:'system.health',handler:async()=>{calls++;return{ok:true}}});const result=await router.execute({tool:'health',session});assert.equal(result.auditId,result.requestId);assert.ok(events.some(e=>e.auditId===result.auditId&&e.requestId===result.requestId));await revokeAdminSession(store,session);await assert.rejects(()=>router.execute({tool:'health',session}),/ADMIN_SESSION_REVOKED/);assert.equal(calls,1)});
});

let server,baseUrl,mode='ok';const nonceFromBody=parsed=>(parsed.messages?.map(m=>m.content).join('\n')||'').match(/LILY-PROOF-[^\s]+/)?.[0]||'unknown';
describe('Muse provider hardened',()=>{
  before(async()=>{server=http.createServer((req,res)=>{if(req.url==='/v1/models'){if(mode==='wrong')return res.end(JSON.stringify({data:[{id:'other-model'}]}));if(mode==='malformed')return res.end('{broken');res.setHeader('Content-Type','application/json');return res.end(JSON.stringify({data:[{id:MODEL_ID}]}))}if(req.url==='/v1/chat/completions'){if(mode==='timeout')return;if(mode==='huge')return res.end('x'.repeat(2*1024*1024+100));let body='';req.on('data',c=>body+=c);req.on('end',()=>{const parsed=JSON.parse(body),content=mode==='empty'?'':nonceFromBody(parsed);res.setHeader('Content-Type','application/json');res.end(JSON.stringify({id:'req-realistic-test',model:MODEL_ID,choices:[{message:{content}}]}))});return}res.statusCode=404;res.end()});await new Promise(r=>server.listen(0,'127.0.0.1',r));baseUrl=`http://127.0.0.1:${server.address().port}/v1`});after(()=>server.close());
  it('pins exact model identity',()=>{assert.equal(new GlimmerProvider({baseUrl,model:'other-model'}).model,MODEL_ID)});
  it('requires exact /models match',async()=>{mode='ok';assert.equal((await new GlimmerProvider({baseUrl}).health()).ok,true);mode='wrong';const h=await new GlimmerProvider({baseUrl}).health();assert.equal(h.ok,false);assert.equal(h.status,'MODEL_ID_MISMATCH')});
  it('rejects malformed and oversized responses',async()=>{mode='malformed';assert.equal((await new GlimmerProvider({baseUrl}).health()).ok,false);mode='huge';await assert.rejects(()=>new GlimmerProvider({baseUrl}).run('hello'),/MODEL_RESPONSE_TOO_LARGE/)});
  it('cancels timed out requests',async()=>{mode='timeout';await assert.rejects(()=>new GlimmerProvider({baseUrl,timeoutMs:150}).run('hello'),/MODEL_REQUEST_TIMEOUT/)});
  it('runs nonce proof against configured endpoint',async()=>{mode='ok';const proof=await runLilyProof(new GlimmerProvider({baseUrl}));assert.equal(proof.ok,true);assert.equal(proof.nonceMatch,true);assert.equal(proof.model,MODEL_ID);assert.equal(proof.requestId,'req-realistic-test')});
  it('rejects plaintext remote endpoints and URL credentials',()=>{assert.throws(()=>new GlimmerProvider({baseUrl:'http://192.0.2.10:8000/v1'}),/PLAINTEXT_REMOTE_FORBIDDEN/);assert.throws(()=>new GlimmerProvider({baseUrl:'https://user:pass@example.com/v1'}),/CREDENTIALS_IN_URL_FORBIDDEN/)});
});

describe('Storage hardening',()=>{
  it('memory consume is one-time under race',async()=>{const s=new MemoryChallengeStore(),c=await s.create('owner-memory-12345678'),out=await Promise.allSettled(Array.from({length:50},()=>s.consume(c.nonce)));assert.equal(out.filter(x=>x.status==='fulfilled').length,1);assert.equal(out.filter(x=>x.status==='rejected').length,49)});
  it('session revocation and expiry are server-side',async()=>{const s=new MemoryChallengeStore();await s.trackSession('owner-memory-12345678','sid',Date.now()+1000,{id:'sid',subject:'owner-memory-12345678',role:'LILY_OWNER_ADMIN',capabilities:['system.health'],expiresAt:Date.now()+1000});assert.equal(await s.isSessionActive('owner-memory-12345678','sid'),true);await s.revokeSession('owner-memory-12345678','sid');assert.equal(await s.isSessionActive('owner-memory-12345678','sid'),false)});
  it('Redis adapter calls atomic Lua for consume/session limit',async()=>{const calls=[],fake={eval:async(...args)=>{calls.push(args);if(String(args[0]).includes("return {'OK',raw}"))return['MISS'];return 1}};const r=new RedisChallengeStore(fake);assert.equal(await r.consume('abc'),null);await r.trackSession('owner','sid',Date.now()+10000,{id:'sid',subject:'owner',role:'LILY_OWNER_ADMIN',capabilities:[],expiresAt:Date.now()+10000});assert.ok(calls[0][0].includes("redis.call('DEL',KEYS[1])"));assert.ok(calls[1][0].includes('SMEMBERS'))});
  it('real Redis stays blocked unless PING succeeds',async()=>{const result=await RedisChallengeStore.tryCreate();if(result.blocked){assert.equal(result.blocked,true);console.log(`REDIS_VERIFIED=BLOCKED - ${result.error}`)}else{assert.equal(await result.redis.ping(),'PONG');console.log('REDIS_VERIFIED=PASS');await result.redis.quit()}});
});

test('adversarial simulation blocks replay escalation and revoked sessions',async()=>{const {publicKey,privateKey}=crypto.generateKeyPairSync('ed25519'),publicKeyPem=publicKey.export({type:'spki',format:'pem'}),privateKeyPem=privateKey.export({type:'pkcs8',format:'pem'}),dev={id:'sim-device',publicKeyPem};let prevented=0;for(let i=0;i<120;i++){const store=new MemoryChallengeStore(),id=`owner-sim-${String(i).padStart(8,'0')}`,ch=await createAdminChallenge(store,id),sig=signEd25519({...ch,privateKeyPem}),session=await issueAdminSession({store,challenge:ch,signedChallenge:sig,authenticatedUser:{id},verifiedDevice:dev});await assert.rejects(()=>issueAdminSession({store,challenge:ch,signedChallenge:sig,authenticatedUser:{id},verifiedDevice:dev}),/CHALLENGE_REPLAYED/);prevented++;const forged={...session,capabilities:[...session.capabilities,'production.deploy']};await assert.rejects(()=>authorizeSession(store,forged,'production.deploy'),/CAPABILITY_DENIED/);prevented++;await revokeAdminSession(store,session);await assert.rejects(()=>authorizeSession(store,session,'system.health'),/ADMIN_SESSION_REVOKED/);prevented++}assert.equal(prevented,360);console.log(`SECURITY_SIM_PASS prevented=${prevented}`)});
