import crypto from 'node:crypto';

export const CONFIG = Object.freeze({
  MODEL:'meta-models/Muse-Glimmer-30B',CHALLENGE_TTL_MS:60_000,RETAIN_USED_MS:300_000,
  ADMIN_SESSION_TTL_MS:600_000,ACTION_CONFIRM_TTL_MS:60_000,MAX_CONCURRENT_SESSIONS:2,
  MAX_ATTEMPTS:5,RATE_WINDOW_MS:60_000,LOCKOUT_MS:300_000,MAX_TOOL_CALLS_PER_MIN:60
});
const nowMs=()=>Date.now();

export class MemoryChallengeStore {
  constructor(){this.challenges=new Map();this.used=new Map();this.failedAttempts=new Map();this.sessions=new Map();this.ownerSessions=new Map();this.confirmations=new Map();this.usedConfirmations=new Map()}
  async isLocked(ownerId){const e=this.failedAttempts.get(ownerId);if(!e)return false;const now=nowMs();if(e.lockedUntil&&now<e.lockedUntil)return true;if(now-e.firstAttempt>CONFIG.RATE_WINDOW_MS)this.failedAttempts.delete(ownerId);return false}
  async recordFailure(ownerId){const now=nowMs();let e=this.failedAttempts.get(ownerId);if(!e||now-e.firstAttempt>CONFIG.RATE_WINDOW_MS)e={count:0,firstAttempt:now,lockedUntil:0};e.count++;if(e.count>=CONFIG.MAX_ATTEMPTS)e.lockedUntil=now+CONFIG.LOCKOUT_MS;this.failedAttempts.set(ownerId,e)}
  async create(ownerId){if(await this.isLocked(ownerId))throw new Error('OWNER_LOCKED');const nonce=crypto.randomBytes(32).toString('hex'),createdAt=nowMs();const challenge={ownerId,nonce,createdAt,expiresAt:createdAt+CONFIG.CHALLENGE_TTL_MS};this.challenges.set(nonce,challenge);return Object.freeze({...challenge})}
  async consume(nonce){const now=nowMs(),usedUntil=this.used.get(nonce);if(usedUntil&&now<usedUntil)throw new Error('CHALLENGE_REPLAYED');if(usedUntil&&now>=usedUntil)this.used.delete(nonce);const stored=this.challenges.get(nonce);if(!stored)return null;this.challenges.delete(nonce);this.used.set(nonce,now+CONFIG.RETAIN_USED_MS);return stored}
  async trackSession(ownerId,sessionId,expiresAt,claims=null){const now=nowMs(),set=this.ownerSessions.get(ownerId)||new Set();for(const id of [...set]){const s=this.sessions.get(id);if(!s||s.revoked||s.expiresAt<=now){set.delete(id);this.sessions.delete(id)}}if(set.size>=CONFIG.MAX_CONCURRENT_SESSIONS)throw new Error('MAX_CONCURRENT_SESSIONS');set.add(sessionId);this.ownerSessions.set(ownerId,set);this.sessions.set(sessionId,{ownerId,expiresAt,revoked:false,claims:claims?structuredClone(claims):null})}
  async getSession(ownerId,sessionId){const s=this.sessions.get(sessionId);if(!s||s.ownerId!==ownerId||s.revoked||s.expiresAt<=nowMs())return null;return s.claims?structuredClone(s.claims):{id:sessionId,subject:ownerId,expiresAt:s.expiresAt}}
  async isSessionActive(ownerId,sessionId){return Boolean(await this.getSession(ownerId,sessionId))}
  async revokeSession(ownerId,sessionId){const s=this.sessions.get(sessionId);if(!s||s.ownerId!==ownerId)return false;s.revoked=true;this.ownerSessions.get(ownerId)?.delete(sessionId);return true}
  async untrackSession(ownerId,sessionId){this.ownerSessions.get(ownerId)?.delete(sessionId);this.sessions.delete(sessionId)}
  async createActionConfirmation({ownerId,sessionId,action,taskId}){const id=crypto.randomUUID(),nonce=crypto.randomBytes(32).toString('hex'),createdAt=nowMs();const r={id,nonce,ownerId,sessionId,action,taskId,createdAt,expiresAt:createdAt+CONFIG.ACTION_CONFIRM_TTL_MS};this.confirmations.set(id,r);return Object.freeze({...r})}
  async consumeActionConfirmation(id){const now=nowMs(),usedUntil=this.usedConfirmations.get(id);if(usedUntil&&now<usedUntil)throw new Error('CONFIRMATION_REPLAYED');const r=this.confirmations.get(id);if(!r)return null;this.confirmations.delete(id);this.usedConfirmations.set(id,now+CONFIG.RETAIN_USED_MS);return r}
}

export class RedisChallengeStore {
  constructor(redis){this.redis=redis}
  static async tryCreate(){try{const mod=await import('ioredis'),IORedis=mod.default||mod;const redis=new IORedis(process.env.REDIS_URL||'redis://127.0.0.1:6379',{connectTimeout:2000,lazyConnect:true,maxRetriesPerRequest:1,enableOfflineQueue:false});await redis.connect();if(await redis.ping()!=='PONG')throw new Error('REDIS_PING_FAIL');return new RedisChallengeStore(redis)}catch(e){return{blocked:true,error:e.message,reason:'ioredis not installed or redis unreachable'}}}
  async create(ownerId){if(await this.isLocked(ownerId))throw new Error('OWNER_LOCKED');const nonce=crypto.randomBytes(32).toString('hex'),createdAt=nowMs();const c={ownerId,nonce,createdAt,expiresAt:createdAt+CONFIG.CHALLENGE_TTL_MS};await this.redis.set(`lily:challenge:${nonce}`,JSON.stringify(c),'PX',CONFIG.CHALLENGE_TTL_MS,'NX');return Object.freeze({...c})}
  async consume(nonce){const script=`if redis.call('EXISTS',KEYS[2])==1 then return {'REPLAY'} end local raw=redis.call('GET',KEYS[1]) if not raw then return {'MISS'} end redis.call('DEL',KEYS[1]) redis.call('SET',KEYS[2],'1','PX',ARGV[1],'NX') return {'OK',raw}`;const out=await this.redis.eval(script,2,`lily:challenge:${nonce}`,`lily:challenge:used:${nonce}`,String(CONFIG.RETAIN_USED_MS));if(out?.[0]==='REPLAY')throw new Error('CHALLENGE_REPLAYED');if(out?.[0]!=='OK')return null;return JSON.parse(out[1])}
  async isLocked(ownerId){return Boolean(await this.redis.get(`lily:lock:${ownerId}`))}
  async recordFailure(ownerId){const script=`if redis.call('EXISTS',KEYS[2])==1 then return -1 end local n=redis.call('INCR',KEYS[1]) if n==1 then redis.call('PEXPIRE',KEYS[1],ARGV[1]) end if n>=tonumber(ARGV[2]) then redis.call('SET',KEYS[2],'1','PX',ARGV[3]) end return n`;await this.redis.eval(script,2,`lily:attempts:${ownerId}`,`lily:lock:${ownerId}`,String(CONFIG.RATE_WINDOW_MS),String(CONFIG.MAX_ATTEMPTS),String(CONFIG.LOCKOUT_MS))}
  async trackSession(ownerId,sessionId,expiresAt,claims=null){const ttl=Math.max(1,expiresAt-nowMs()),payload=JSON.stringify(claims||{id:sessionId,subject:ownerId,expiresAt});const script=`local ids=redis.call('SMEMBERS',KEYS[1]) local active=0 for _,id in ipairs(ids) do if redis.call('EXISTS','lily:session:'..id)==1 then active=active+1 else redis.call('SREM',KEYS[1],id) end end if active>=tonumber(ARGV[3]) then return 0 end redis.call('SET',KEYS[2],ARGV[1],'PX',ARGV[2],'NX') redis.call('SADD',KEYS[1],ARGV[4]) redis.call('PEXPIRE',KEYS[1],ARGV[2]) return 1`;const ok=await this.redis.eval(script,2,`lily:sessions:${ownerId}`,`lily:session:${sessionId}`,payload,String(ttl),String(CONFIG.MAX_CONCURRENT_SESSIONS),sessionId);if(Number(ok)!==1)throw new Error('MAX_CONCURRENT_SESSIONS')}
  async getSession(ownerId,sessionId){const raw=await this.redis.get(`lily:session:${sessionId}`);if(!raw)return null;try{const claims=JSON.parse(raw);return claims.subject===ownerId?claims:null}catch{return null}}
  async isSessionActive(ownerId,sessionId){return Boolean(await this.getSession(ownerId,sessionId))}
  async revokeSession(ownerId,sessionId){const script=`local raw=redis.call('GET',KEYS[2]) if not raw then return 0 end local ok,claims=pcall(cjson.decode,raw) if not ok or claims['subject']~=ARGV[1] then return 0 end redis.call('DEL',KEYS[2]) redis.call('SREM',KEYS[1],ARGV[2]) return 1`;return Number(await this.redis.eval(script,2,`lily:sessions:${ownerId}`,`lily:session:${sessionId}`,ownerId,sessionId))===1}
  async untrackSession(ownerId,sessionId){return this.revokeSession(ownerId,sessionId)}
  async createActionConfirmation({ownerId,sessionId,action,taskId}){const id=crypto.randomUUID(),nonce=crypto.randomBytes(32).toString('hex'),createdAt=nowMs();const r={id,nonce,ownerId,sessionId,action,taskId,createdAt,expiresAt:createdAt+CONFIG.ACTION_CONFIRM_TTL_MS};await this.redis.set(`lily:confirm:${id}`,JSON.stringify(r),'PX',CONFIG.ACTION_CONFIRM_TTL_MS,'NX');return Object.freeze({...r})}
  async consumeActionConfirmation(id){const script=`if redis.call('EXISTS',KEYS[2])==1 then return {'REPLAY'} end local raw=redis.call('GET',KEYS[1]) if not raw then return {'MISS'} end redis.call('DEL',KEYS[1]) redis.call('SET',KEYS[2],'1','PX',ARGV[1],'NX') return {'OK',raw}`;const out=await this.redis.eval(script,2,`lily:confirm:${id}`,`lily:confirm:used:${id}`,String(CONFIG.RETAIN_USED_MS));if(out?.[0]==='REPLAY')throw new Error('CONFIRMATION_REPLAYED');if(out?.[0]!=='OK')return null;return JSON.parse(out[1])}
}
